[tool.poetry]
name = "query-service"
version = "0.1.0" # LLM_COMMENT: Consider bumping version after refactoring
description = "Query service for SaaS B2B using Haystack RAG"
authors = ["Nyro <dev@nyro.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.28.0"}
gunicorn = "^21.2.0"
pydantic = {extras = ["email"], version = "^2.6.4"}
pydantic-settings = "^2.2.1"
httpx = "^0.27.0"
asyncpg = "^0.29.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
tenacity = "^8.2.3"
structlog = "^24.1.0"

# --- Haystack Dependencies ---
haystack-ai = "^2.0.1" # Core Haystack
# openai = "^1.14.3"     # LLM_COMMENT: Removed OpenAI dependency as we switch to FastEmbed
pymilvus = "^2.4.1"    # Cliente Milvus explícito
milvus-haystack = "^0.0.6" # Integración Milvus para Haystack 2.x
fastembed-haystack = "^0.1.1" # LLM_COMMENT: Added FastEmbed Haystack integration

# --- Gemini Dependency ---
google-generativeai = "^0.5.4" # Cliente oficial de Google para Gemini

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-asyncio = "^0.21.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"