# .github/workflows/CICD.yml
name: CI/CD Pipeline Docker -> Manifest Update (Ingest, Query & Gateway - Selective Build)

on:
  push:
    branches: [ "develop" ] # Ejecutar solo en pushes a la rama develop

env:
  # --- Configuración General ---
  REGISTRY: ghcr.io
  MANIFEST_REPO_OWNER: dev-nyro
  MANIFEST_REPO_NAME: manifests-nyro
  MANIFEST_REPO_BRANCH: develop

  # --- Configuración Específica de Servicios ---
  # Directorios en el repo de código fuente
  INGEST_SERVICE_DIR: ingest-service
  QUERY_SERVICE_DIR: query-service
  GATEWAY_SERVICE_DIR: api-gateway

  # Nombres COMPLETOS de las imágenes (incluyendo registro y owner) - SIN TAG
  INGEST_IMAGE_NAME: ghcr.io/dev-nyro/ingest-service
  QUERY_IMAGE_NAME: ghcr.io/dev-nyro/query-service
  GATEWAY_IMAGE_NAME: ghcr.io/dev-nyro/api-gateway

  # --- Rutas RELATIVAS a los archivos de deployment DENTRO del repo de manifests ---
  # ¡¡¡CRÍTICO!!! Asegúrate que estas rutas sean EXACTAS a la estructura de tu repo 'manifests-nyro'
  INGEST_MANIFEST_PATH_API_REL: ingest-service/deployment-api.yaml
  INGEST_MANIFEST_PATH_WORKER_REL: ingest-service/deployment-worker.yaml # Dejar vacío "" si no hay worker manifest
  QUERY_MANIFEST_PATH_REL: query-service/deployment.yaml
  GATEWAY_MANIFEST_PATH_REL: api-gateway/deployment.yaml # Asegúrate que este es el path correcto en manifests-nyro

jobs:
  # Job 1: Construir imágenes Docker si hay cambios y empujarlas a GHCR
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Para checkout
      packages: write # Para push a GHCR

    outputs:
      ingest_built: ${{ steps.build_ingest.outputs.digest != '' }}
      query_built: ${{ steps.build_query.outputs.digest != '' }}
      gateway_built: ${{ steps.build_gateway.outputs.digest != '' }}
      image_tag: ${{ steps.image_tag_common.outputs.image_tag }}

    steps:
      # 1. Checkout del código fuente de la aplicación
      - name: Checkout Application Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Detectar archivos modificados
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            ingest:
              - '${{ env.INGEST_SERVICE_DIR }}/**'
            query:
              - '${{ env.QUERY_SERVICE_DIR }}/**'
            gateway:
              - '${{ env.GATEWAY_SERVICE_DIR }}/**'

      # 3. Configurar Docker Buildx
      - name: Set up Docker Buildx
        if: steps.changed_files.outputs.ingest_any_changed == 'true' || steps.changed_files.outputs.query_any_changed == 'true' || steps.changed_files.outputs.gateway_any_changed == 'true'
        uses: docker/setup-buildx-action@v3

      # 4. Login a GHCR
      - name: Log in to GitHub Container Registry
        if: steps.changed_files.outputs.ingest_any_changed == 'true' || steps.changed_files.outputs.query_any_changed == 'true' || steps.changed_files.outputs.gateway_any_changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Generar etiqueta común
      - name: Generate Common Image Tag
        if: steps.changed_files.outputs.ingest_any_changed == 'true' || steps.changed_files.outputs.query_any_changed == 'true' || steps.changed_files.outputs.gateway_any_changed == 'true'
        id: image_tag_common
        run: |
          TAG="${{ github.ref_name }}-$(echo $GITHUB_SHA | cut -c1-7)"
          TAG=$(echo "$TAG" | sed -e 's/[^a-zA-Z0-9.-]/-/g' -e 's/^[.-]*//' -e 's/[.-]*$//')
          TAG=${TAG::128}
          echo "Generated Common Tag: $TAG"
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT

      # 6. Build/Push Ingest Service
      - name: Build and push Ingest Service Docker image
        id: build_ingest
        if: steps.changed_files.outputs.ingest_any_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.INGEST_SERVICE_DIR }}
          file: ./${{ env.INGEST_SERVICE_DIR }}/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.INGEST_IMAGE_NAME }}:${{ steps.image_tag_common.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 7. Build/Push Query Service
      - name: Build and push Query Service Docker image
        id: build_query
        if: steps.changed_files.outputs.query_any_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.QUERY_SERVICE_DIR }}
          file: ./${{ env.QUERY_SERVICE_DIR }}/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.QUERY_IMAGE_NAME }}:${{ steps.image_tag_common.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 8. Build/Push API Gateway
      - name: Build and push API Gateway Docker image
        id: build_gateway
        if: steps.changed_files.outputs.gateway_any_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.GATEWAY_SERVICE_DIR }}
          file: ./${{ env.GATEWAY_SERVICE_DIR }}/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.GATEWAY_IMAGE_NAME }}:${{ steps.image_tag_common.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Job 2: Actualizar los manifiestos en el repo 'manifests-nyro'
  update-manifests:
    needs: build-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (needs.build-push.outputs.ingest_built == 'true' || needs.build-push.outputs.query_built == 'true' || needs.build-push.outputs.gateway_built == 'true')

    steps:
      # 1. Checkout del repositorio de manifests
      - name: Checkout Manifests Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFEST_REPO_OWNER }}/${{ env.MANIFEST_REPO_NAME }}
          ref: ${{ env.MANIFEST_REPO_BRANCH }}
          token: ${{ secrets.MANIFEST_PAT }}
          path: manifests-repo

      # 2. Usar el tag común generado en el job anterior
      - name: Set Common Image Tag from previous job output
        id: image_tag_common
        run: echo "image_tag=${{ needs.build-push.outputs.image_tag }}" >> $GITHUB_OUTPUT

      # 3. Actualizar archivos de Manifest condicionalmente usando sed
      - name: Update Manifest Files Conditionally
        id: update_manifest
        env:
          INGEST_BUILT: ${{ needs.build-push.outputs.ingest_built }}
          QUERY_BUILT: ${{ needs.build-push.outputs.query_built }}
          GATEWAY_BUILT: ${{ needs.build-push.outputs.gateway_built }}
          COMMON_TAG: ${{ steps.image_tag_common.outputs.image_tag }}
          INGEST_API_MANIFEST_PATH: ${{ env.INGEST_MANIFEST_PATH_API_REL }}
          INGEST_WORKER_MANIFEST_PATH: ${{ env.INGEST_MANIFEST_PATH_WORKER_REL }}
          QUERY_MANIFEST_PATH: ${{ env.QUERY_MANIFEST_PATH_REL }}
          GATEWAY_MANIFEST_PATH: ${{ env.GATEWAY_MANIFEST_PATH_REL }}
          INGEST_IMAGE: ${{ env.INGEST_IMAGE_NAME }}
          QUERY_IMAGE: ${{ env.QUERY_IMAGE_NAME }}
          GATEWAY_IMAGE: ${{ env.GATEWAY_IMAGE_NAME }}
        run: |
          echo "::group::Updating Manifest Files Conditionally"
          cd manifests-repo
          # ... (logs iniciales omitidos por brevedad) ...

          MANIFEST_UPDATED=false
          UPDATE_FAILED=false

          # --- Función para actualizar la línea 'image:' en un archivo YAML (CORREGIDA + DEBUG) ---
          update_image() {
            local manifest_path="$1"
            local target_image="$2" # Imagen completa con tag
            local image_base_name=$(echo "$target_image" | cut -d: -f1) # Extraer nombre base

            echo "Attempting to update image in '$manifest_path' to: $target_image"

            if [ ! -f "$manifest_path" ]; then
              echo "ERROR: Manifest file '$manifest_path' not found!"
              UPDATE_FAILED=true
              return 1
            fi

            # *** CORRECCIÓN PATRÓN SED Y DEBUG ***
            # Patrón sed: Usa [[:space:]] para cualquier espacio en blanco (más robusto que \s)
            # ^([[:space:]]*) -> Captura grupo 1: Cualquier espacio en blanco al inicio (indentación)
            # image:[[:space:]]+ -> Literal 'image:' seguido de uno o más espacios
            # ${...}         -> Nombre base de la imagen (escapando '/')
            # :.*$           -> Literal ':' seguido de cualquier caracter hasta el final (tag viejo)
            local sed_pattern="^([[:space:]]*)image:[[:space:]]+${image_base_name//\//\\/}:.*$"

            # Reemplazo sed:
            # \1             -> Reinserta la indentación capturada (grupo 1)
            # image:         -> Literal 'image:' (con espacio normal después)
            # ${target_image} -> La imagen completa con el nuevo tag
            local sed_replacement="\1image: ${target_image}"

            echo "Using sed pattern: $sed_pattern"
            echo "Using sed replacement: $sed_replacement"

            # DEBUG: Mostrar la línea que coincide ANTES de reemplazar (si existe)
            echo "--- Line(s) matching pattern in '$manifest_path' BEFORE sed ---"
            grep -E "$sed_pattern" "$manifest_path" || echo "No matching lines found by grep."
            echo "--------------------------------------------------------------"

            # Comprobar si el patrón existe antes de intentar reemplazar
            if grep -qE "$sed_pattern" "$manifest_path"; then
               echo "Found image line matching pattern in '$manifest_path'. Attempting replacement..."
               # Usar sed con el patrón y reemplazo corregidos. Usar delimitador @.
               if sed -i.bak -E "s@${sed_pattern}@${sed_replacement}@" "$manifest_path"; then
                  # DEBUG: Mostrar la línea DESPUÉS de reemplazar
                  echo "--- Line(s) matching pattern in '$manifest_path' AFTER sed ---"
                  grep -E "^([[:space:]]*)image:[[:space:]]+${image_base_name//\//\\/}:${COMMON_TAG}$" "$manifest_path" || echo "No matching lines found by grep AFTER sed (might indicate issue)."
                  echo "-------------------------------------------------------------"

                  if ! cmp -s "$manifest_path" "$manifest_path.bak"; then
                    echo "Successfully updated image in '$manifest_path' to '$target_image'"
                    MANIFEST_UPDATED=true
                  else
                    # Esto puede pasar si el tag ya era el correcto
                    echo "Image in '$manifest_path' was already up-to-date or sed command did not change the file."
                  fi
                  rm -f "$manifest_path.bak"
                  return 0
               else
                  echo "ERROR: sed command failed for '$manifest_path'"
                  rm -f "$manifest_path.bak"
                  UPDATE_FAILED=true
                  return 1
               fi
            else
                echo "WARNING: Pattern '$sed_pattern' not found by grep -qE in '$manifest_path'. Skipping update for this file."
                return 0
            fi
          } # --- Fin de la función update_image ---

          # --- Update Ingest Service ---
          if [ "$INGEST_BUILT" = "true" ]; then
            INGEST_TARGET_IMAGE="${INGEST_IMAGE}:${COMMON_TAG}"
            update_image "$INGEST_API_MANIFEST_PATH" "$INGEST_TARGET_IMAGE"
            if [ -n "$INGEST_WORKER_MANIFEST_PATH" ]; then
               update_image "$INGEST_WORKER_MANIFEST_PATH" "$INGEST_TARGET_IMAGE"
            fi
          else
            echo "Skipping Ingest Service manifest update (not built)."
          fi

          # --- Update Query Service ---
          if [ "$QUERY_BUILT" = "true" ]; then
            QUERY_TARGET_IMAGE="${QUERY_IMAGE}:${COMMON_TAG}"
            update_image "$QUERY_MANIFEST_PATH" "$QUERY_TARGET_IMAGE"
          else
            echo "Skipping Query Service manifest update (not built)."
          fi

          # --- Update API Gateway ---
          if [ "$GATEWAY_BUILT" = "true" ]; then
            GATEWAY_TARGET_IMAGE="${GATEWAY_IMAGE}:${COMMON_TAG}"
            echo "Updating Gateway Manifest: Path='$GATEWAY_MANIFEST_PATH', Target Image='$GATEWAY_TARGET_IMAGE'"
            update_image "$GATEWAY_MANIFEST_PATH" "$GATEWAY_TARGET_IMAGE" # Usar la función corregida
          else
            echo "Skipping API Gateway manifest update (not built)."
          fi

          # ... (resto del script: exportar outputs, git status, check de errores) ...
          echo "Final Manifest Updated Status: $MANIFEST_UPDATED"
          echo "manifest_updated=$MANIFEST_UPDATED" >> $GITHUB_OUTPUT
          echo "--- Checking Git Status Before Commit ---"
          git status
          if [ "$UPDATE_FAILED" = "true" ]; then
            echo "::error::One or more manifest updates failed critically. Please check logs."
            exit 1
          fi
          echo "::endgroup::"

      # 4. Commit y Push de los Cambios del Manifest
      - name: Commit and Push Manifest Changes
        if: steps.update_manifest.outcome == 'success' && steps.update_manifest.outputs.manifest_updated == 'true'
        run: |
          # ... (commit/push logic sin cambios) ...
          echo "::group::Committing and Pushing Manifest Changes"
          cd manifests-repo
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No actual manifest changes staged. Skipping commit."
          else
            echo "Manifest changes detected. Committing..."
            COMMIT_MSG="Update service image(s) to tag ${{ steps.image_tag_common.outputs.image_tag }} [CI]"
            git commit -m "$COMMIT_MSG"
            echo "Pushing changes to origin/${{ env.MANIFEST_REPO_BRANCH }}..."
            git push origin ${{ env.MANIFEST_REPO_BRANCH }} || (sleep 5 && git push origin ${{ env.MANIFEST_REPO_BRANCH }})
            echo "Push successful."
          fi
          echo "::endgroup::"
